// Generated by Saber 0.2.1

// swiftlint:disable all

import Foundation

internal class BinderContainer: BinderContaining {

    internal init() {
    }

    internal var bNetworkManager: BNetworkManager {
        let bNetworkManager = self.makeBNetworkManager()
        return bNetworkManager
    }

    internal var bConsoleLogger: BConsoleLogger {
        let bConsoleLogger = self.makeBConsoleLogger()
        return bConsoleLogger
    }

    internal var bLogging: BLogging {
        return self.bConsoleLogger
    }

    private func makeBNetworkManager() -> BNetworkManager {
        return BNetworkManager(bConsoleLogger: self.bConsoleLogger)
    }

    private func makeBConsoleLogger() -> BConsoleLogger {
        return BConsoleLogger()
    }

}