// Generated by Saber 0.2.1

// swiftlint:disable all

import Foundation

internal class briefContainer: brief {

    internal init() {
    }

    internal var bar: Bar {
        let bar = self.makeBar()
        return bar
    }

    internal var foo: Foo {
        let foo = self.makeFoo()
        return foo
    }

    private func makeBar() -> Bar {
        return Bar()
    }

    private func makeFoo() -> Foo {
        return Foo()
    }

}