// Generated by Saber 0.2.1

// swiftlint:disable all

import Foundation

internal class BriefContainer: BriefContaning {

    internal init() {
    }

    internal var foo: Foo {
        let foo = self.makeFoo()
        return foo
    }

    internal var user: User {
        let user = self.makeUser()
        return user
    }

    internal var bar: Bar {
        let bar = self.makeBar()
        return bar
    }

    private func makeFoo() -> Foo {
        return Foo()
    }

    private func makeUser() -> User {
        return User(name: self.bar)
    }

    private func makeBar() -> Bar {
        return Bar(foo: self.foo)
    }

}