// Generated by Saber 0.2.1

// swiftlint:disable all

import Foundation

internal class BriefContainer: BriefContaning {

    internal init() {
    }

    internal var foo: Foo {
        let foo = self.makeFoo()
        return foo
    }

    private func makeFoo() -> Foo {
        return Foo()
    }

}