// Generated by Saber 0.2.1

// swiftlint:disable all

import Foundation

internal class containerInjectionContainer: ContainerInjectionContaining {

    internal init() {
    }

    internal var cIFoo: CIFoo {
        let cIFoo = self.makeCIFoo()
        self.injectTo(cIFoo: cIFoo)
        return cIFoo
    }

    private func makeCIFoo() -> CIFoo {
        return CIFoo()
    }

    private func injectTo(cIFoo: CIFoo) {
        cIFoo.container = self
    }

}