// Generated by Saber 0.2.1

// swiftlint:disable all

import Foundation

internal class ProviderContainer: ProviderContaining {

    internal init() {
    }

    internal var testProvider: TestProvider {
        let testProvider = self.makeTestProvider()
        return testProvider
    }

    internal var loggerProvider: LoggerProvider {
        let loggerProvider = self.makeLoggerProvider()
        return loggerProvider
    }

    internal var logging: Logging {
        let logging = self.makeLogging()
        return logging
    }

    private func makeTestProvider() -> TestProvider {
        return TestProvider(logging: self.logging)
    }

    private func makeLoggerProvider() -> LoggerProvider {
        return LoggerProvider()
    }

    private func makeLogging() -> Logging {
        let provider = self.loggerProvider
        return provider.provide()
    }

}