// Generated by Saber 0.2.1

// swiftlint:disable all

import Foundation

internal class UserContainer: UserContaining {

    internal unowned let appsContainer: AppsContainer

    internal let userId: UserId

    internal init(appsContainer: AppsContainer, userId: UserId) {
        self.appsContainer = appsContainer
        self.userId = userId
    }

    internal var userManager: UserManager {
        let userManager = self.makeUserManager()
        return userManager
    }

    internal var user: User {
        let user = self.makeUser()
        return user
    }

    private func makeUserManager() -> UserManager {
        return UserManager(database: self.appsContainer.database, userId: self.userId)
    }

    private func makeUser() -> User {
        return User()
    }

}